baseURL = "/"
languageCode = "en-us"
title = "Analysis of NRL"
theme = "hyde-hyde"

[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 1
    url = "/portfolio/"
    
[[menu.main]]
    name = "About"
    identifier = "About"
    weight = 2
    url = "/about/"    