baseURL = "/"
languageCode = "en-us"
title = "Analysis of NRL"
theme = "hyde-hyde"

[Params]
    intro = true
    description = "Variance Semi- Explained"

[params.social]
  	twitter = "htr3n"
  	keybase = "htr3n"
  	github = "htr3n"


[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 1
    url = "/portfolio/"
    
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 2
    url = "/about/"    